### ISSUE TITLE
No products are getting imported 

### ISSUE THREAD

**Issue by HeshamIsmail** [Knawat/dropshipping-woocommerce#193]
**Describe the bug**

The store is unable to import any products and getting errors in their log file.

**To Reproduce**
1. Go to Dropshipping plugin
2. Import products

**Result**

No products are getting imported 

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/74185849/113861533-fdea6500-97af-11eb-99f0-92db5c0f42c3.png)

**Enviroment (please complete the following information):**
 - OS: Windows 10
 - Browser Google Chrome
 - Plugin Version 2.2.0
 - WordPress Version 5.7
 - WooCommerce Version [e.g. 5.2]

**Additional context**

**Comment by suraj-rathod** [comment]
@HeshamIsmail checked product import functionality on the customer store  so after disabling the product category = none it's working and when i turn it as a category then import functionality is not working so need to recheck while the category is enabled

![image](https://user-images.githubusercontent.com/36834155/113902538-9fdc7280-97ed-11eb-9841-922f6e966e7d.png)

**Comment by suraj-rathod** [comment]
@HeshamIsmail I have checked the plugin and Database in the web store so i couldn't find any issue with our plugin i think it's related to the web store might be a database or some plugin conflict because from admin i can not create any category please review below video you will get the idea.
https://www.screencast.com/t/YgFy8rYYk32

So, I need to check the fully store and database also.

![image](https://user-images.githubusercontent.com/36834155/114199886-52d5d900-9972-11eb-8d4c-c0209a6aad48.png)

**Comment by HeshamIsmail** [comment]
As it's not caused by Knawat there is no need to further working on this issue.

Thank you
