### ISSUE TITLE
Add option for full product update ( Force Update )

### ISSUE THREAD

**Issue by iamdharmesh** [Knawat/dropshipping-woocommerce#25]
### Acceptance Criteria:
- [ ] User can click a button in the edit product page to force aggregate info from Knawat API
- [ ] User can select multiple products and click update from Knawat Button to fetch updated info
- [ ] This button should update all fields including title, description, variations, and images

**Comment by iamdharmesh** [comment]
@HeshamIsmail please help to test this.

**Comment by HeshamIsmail** [comment]
Testing subject:

Testing without qtranslatex the  "Update from Knawat" feature from all products in order to confirm the three acceptance criteria:

-  User can click a button on the edit product page to force aggregate info from Knawat API
-  User can select multiple products and click update from Knawat Button to fetch updated info
-  This button should update all fields including title, description, variations, and images

Testing steps:

1-Opened all products page on Woocommerce.
2-Selected all products on the first page (20 products).
3-From "Bulk action", I applied "Update from Knawat"

**Result:20 Knawat product(s) has been updated successfully.**

4-Changed the title for few products.
5-Deleted few images.
6-Selected all products on the first page (20 products).
7-From "Bulk action", I applied "Update from Knawat"

**Result: 20 Knawat product(s) have been updated successfully.
The images were uploaded back to each product and the title was fixed.**

Proceeding with testing using qtranslatex plugin tomorrow.
