### ISSUE TITLE
Delete out of stock products automatically

### ISSUE THREAD

**Issue by HazemKhaled** [Knawat/dropshipping-woocommerce#65]
### Description:
Some customers asking to delete out of stock products, not only in the trash, even clean up from the trash to keep their website clean from out of stock products.

### Acceptance Criteria:

- [ ] Checkbox in Knawat Plugin Settings to delete out of stock products (Default unchecked)
- [ ] Add note: "Some products go out of stock and return back. If you checked this, products will not return back to your store."
- [ ] Write help page and send to Customer Support to add in help.knawat.com

**Comment by suraj-rathod** [comment]
@HeshamIsmail Please test it

**Comment by HeshamIsmail** [comment]
The feature is not working.

Testing steps:

1.Updated the dropshipping-Woocommerce-master plug-in to integrate with https://dev.mp.knawat.io/api instead of https://mp.knawat.io/api
2.Installed the plugin on Woocommerce and imported 30 products from https://dev.app.knawat.io/.
3.Nirali set the product: W1C-58950-73-23-3936 as out of stock 
4.Waited till all products were updated.

Result: The product wasn't deleted.

6.Updated  the product by Knawat

Result: The product wasn't deleted.

@suraj-rathod , @iamdharmesh  please kindly check

**Comment by suraj-rathod** [comment]
@HeshamIsmail Can you please review it again because today I have checked with all way and it's working and as well as i have explained to you over call and you have also seen a product with zero quantity is deleted but as we discussed some time we have cache issue @iamdharmesh in the API so might be this reason product will not display updated and you faced an issue.

**Comment by HeshamIsmail** [comment]
We tested the scenarios below and the result needs further investigation:

**A**)1. We imported W1TK-62960-68-10-11971 then archived the product on https://dev.app.knawat.io/

Result: the product wasn't set to out of stock either deleted from the products list on Woocommerce

2.We waited for the products to be updated however **the product stayed in stock.**
3.We applied bulk action "Knawat update" however **the product stayed in stock and still not deleted**.
4.We opened the product on Woocommerce and clicked on "Get from Knawat", **the product was deleted**.

**B**)1. We imported W1TK-621110-142-21-11949 then archived the product on https://dev.app.knawat.io/

Result: the product wasn't set to out of stock either deleted from the products list on Woocommerce

2.We waited for the products to be updated however **the product stayed in stock.**
3.We applied bulk action "Knawat update" however **the product stayed in stock and still not deleted**.
4.On API the product is archived as per the **Curl** below:

curl --location --request GET 'https://dev.mp.knawat.io/api/catalog/products/W1TK-621110-142-21-11949' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE5YjU2MmYwLTgzMTktMTFlYi1hN2VhLTNmZDA1N2NiN2YzMCIsImV4cCI6MTYyMzE1MTQ2OCwiaWF0IjoxNjE3OTY3NDY4fQ.s9qmS6MiYoX0SmmwtHfRM5uYnRe6zMRpTepMZup10A0'

**Comment by HeshamIsmail** [comment]
1. We imported A2KP17A7411200945 then archived the product on https://dev.app.knawat.io/
2.We waited for the products to be updated (synched).

Result: the product was set to out of stock as supposed but not deleted from Woocommerce

3.We applied bulk action "Knawat update" however **the product still not deleted**.
4.On API the product is archived as per the Curl below:

curl --location --request GET 'https://dev.mp.knawat.io/api/catalog/products/A2KP17A7411200945' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkYTBkMzEwLTlkZTMtMTFlYi1hNDIzLWM3MzcwYThiNTE3NyIsImV4cCI6MTYyMzc0NDc0NCwiaWF0IjoxNjE4NTYwNzQ0fQ.f41rdFv7jnqS6EuucZheYFY4oX2vGHfz0Xk06ReV9kU'

5.Still the only way to delete an out-of-stock product is from the "Get from Knawat" button inside the product.

Kindly please check @suraj-rathod

**Comment by HeshamIsmail** [comment]
As per my tests, the out of stock products were deleted as supposed in the following scenarios:

1-Update by Knawat bulk action.
2-Sync all products.
3-Get from Knawat inside the product.

All criteria are met, closing the issue.
